/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsListPets } from "../../funcs/petsListPets.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RequestListPetsRequest$inboundSchema,
};

export const tool$petsListPets: ToolDefinition<typeof args> = {
  name: "pets-list-pets",
  description: `List all pets`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petsListPets(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
