/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsGetCount } from "../../funcs/statsGetCount.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$statsGetCount: ToolDefinition = {
  name: "stats-get-count",
  description: `Get count`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await statsGetCount(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
