/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsGetRandom } from "../../funcs/statsGetRandom.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$statsGetRandom: ToolDefinition = {
  name: "stats-get-random",
  description: `Get random integer`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await statsGetRandom(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
