/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsGetCount } from "../funcs/statsGetCount.js";
import { statsGetRandom } from "../funcs/statsGetRandom.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Stats extends ClientSDK {
  /**
   * Get count
   */
  async getCount(
    options?: RequestOptions,
  ): Promise<operations.GetCountResponse> {
    return unwrapAsync(statsGetCount(
      this,
      options,
    ));
  }

  /**
   * Get random integer
   */
  async getRandom(
    options?: RequestOptions,
  ): Promise<operations.GetRandomResponse> {
    return unwrapAsync(statsGetRandom(
      this,
      options,
    ));
  }
}
