workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: overlay.yaml
        output: combined-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/openapi
targets:
    overlay-example:
        target: typescript
        source: openapi
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/openapi-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
