name: Generate SDK for PR
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: true

env:
  SPEAKEASY_CLI_LOCATION: /home/runner/work/changelog-test-repo/changelog-test-repo/bin/speakeasy
  SPEAKEASY_CHANGELOG_DIR: /home/runner/work/changelog-test-repo/changelog-test-repo/changelog-dir

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create changelog directory
        run: |
          mkdir -p changelog-dir
          echo "current working directory - $(pwd)"
          echo "Created changelog directory at $(pwd)/changelog-dir"

      - name: Download binary from release
        run: |
          echo "current working directory before mkdir  - $(pwd)"
          mkdir -p bin
          echo "current working directory - $(pwd)"
          echo "Downloading speakeasy binary to: $(pwd)/bin/speakeasy"
          curl -L -o bin/speakeasy https://github.com/speakeasy-api/changelog-test-repo/releases/download/v0.0.3/speakeasy
          chmod +x bin/speakeasy
          echo "github workspace - ${{ github.workspace }}"
          echo "current working directory - $(pwd)"
          echo "Full binary path: $(realpath bin/speakeasy)"
          echo "Files in bin directory ->"
          ls -la bin/
          echo "Files in pwd directory ->"
          ls -la .
          echo "=== End of bin directory contents ==="
          echo "SPEAKEASY_CLI_LOCATION=${{ github.workspace }}/bin/speakeasy" >> $GITHUB_ENV
          echo "SPEAKEASY_CHANGELOG_DIR=${{ github.workspace }}/changelog-dir" >> $GITHUB_ENV


      - name: Debug Environment Variables
        run: |
          echo "SPEAKEASY_CLI_LOCATION: ${{ env.SPEAKEASY_CLI_LOCATION }}"
          echo "SPEAKEASY_CHANGELOG_DIR: ${{env.SPEAKEASY_CHANGELOG_DIR}}"
          echo "SPEAKEASY_CLI_LOCATION: $(env.SPEAKEASY_CLI_LOCATION)"
          echo "SPEAKEASY_CHANGELOG_DIR: $(env.SPEAKEASY_CHANGELOG_DIR)"

      - name: Build and run custom SDK action
        run: |
          # Clone the repository with your changes
          git clone https://github.com/speakeasy-api/sdk-generation-action.git /tmp/sdk-action
          cd /tmp/sdk-action
          git checkout changelog-additions-removals
          
          # Build the Docker image
          docker build -t custom-sdk-action .
          
          # Run the container with your environment variables
          docker run --rm \
            -e SPEAKEASY_CLI_LOCATION="${{ github.workspace }}/bin/speakeasy" \
            -e SPEAKEASY_CHANGELOG_DIR="${{ github.workspace }}/changelog-dir" \
            -e GITHUB_ACCESS_TOKEN="${{ secrets.SPEAKEASY_WORKFLOW_GITHUB_PAT }}" \
            -e SPEAKEASY_API_KEY="${{ secrets.SPEAKEASY_API_KEY }}" \
            -e MODE=pr \
            -e FORCE=true \
            -e TARGET=overlay-example \
            -v "${{ github.workspace }}:${{ github.workspace }}" \
            -w "${{ github.workspace }}" \
            custom-sdk-action