name: Generate SDK
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: true
      set_version:
        description: optionally set a specific SDK version
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download binary from release
        run: |
          mkdir -p bin
          curl -L -o bin/speakeasy https://github.com/speakeasy-api/changelog-test-repo/releases/download/v0.0.1/speakeasy
          chmod +x bin/speakeasy

      - name: Generate SDK
        id: generate
        uses: speakeasy-api/sdk-generation-action@changelog-additions-removals
        env:
          SPEAKEASY_CLI_LOCATION: ${{ github.workspace }}/bin/speakeasy
        with:
          speakeasy_version: latest
          github_access_token: ${{ secrets.SPEAKEASY_WORKFLOW_GITHUB_PAT }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          mode: pr
          force: ${{ inputs.force }}
          target: overlay-example
          set_version: ${{ inputs.set_version }}