name: Generate SDK
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: true
      set_version:
        description: optionally set a specific SDK version
        type: string
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: true
      mode: pr
      speakeasy_version: latest
      target: overlay-example
    secrets:
      # token for kanwar speakeasy 
      github_access_token: ${{ secrets.SPEAKEASY_WORKFLOW_GITHUB_PAT }}
      # speakeasy api key for kanwar
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}