name: Publish Nothing
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
      - "*/RELEASES.md"
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: true
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@testing-sdk-action-v1
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: "jkasndiu1h281237anslkd"
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}